sensors:
  - kinect_pointcloud

kinect_pointcloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /scene_cloud
  max_range: 5.0
  octomap_resolution: 0.02
  point_subsample: 1
  padding_offset: 0.1
  padding_scale: 2.0
  max_update_rate: 5.0
  filtered_cloud_topic: filtered_cloud
