# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  trajectory_execution.trajectory_duration_monitoring: False
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller
    - joint_trajectory_controller
    - gripper_controller

  scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: false
  gripper_controller:
    type: GripperCommand
    joints:
      - finger_joint
      - left_outer_finger_joint
      - left_inner_finger_joint
      - left_inner_finger_pad_joint
      - left_inner_knuckle_joint
      - right_inner_knuckle_joint
      - right_outer_knuckle_joint
      - right_outer_finger_joint
      - right_inner_finger_joint
      - right_inner_finger_pad_joint
    action_ns: gripper_action
    default: true
